@startuml entity_lifecycle

participant Engine

group Creation

	LogicEngine -> Engine : postNewEntity

	Engine -> LogicEngine : postLogicMessage
	Engine -> GraphicEngine : postGraphicMessage

end

group Update

	LogicEngine -> Engine : postUpdateEntity

	Engine -> GraphicEngine : postGraphicMessage

end

group Delete

	LogicEngine -> Engine : postDeleteEntity

	Engine -> LogicEngine : postLogicMessage
	Engine -> GraphicEngine : postGraphicMessage

end

@enduml
