@startuml entity

package engine
{
class Entity
class Scene

package logic
{
	class LogicEntity
}
package graphic
{
	class GraphicEntity
	class Resource
}
package physic
{
	class PhysicEntity
	class HitBox
}

Entity -* "1" LogicEntity : logicEntity
Entity -* "1" GraphicEntity : graphicEntity
Entity -* "1" PhysicEntity : physicEntity

Scene -o "*" Entity : entities

GraphicEntity -o "1" Resource : resource
GraphicEntity : std::string state
GraphicEntity : float frame
GraphicEntity : Ogre::Item item
GraphicEntity : Ogre::SceneNode node (item->getParentNode())


Resource : Model model

PhysicEntity -* HitBox : hitbox
}

@enduml
